version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: my_tailor
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: